name: Delete EKS Cluster and Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_delete:
        description: 'Type "DELETE" to confirm the deletion of the entire infrastructure'
        required: true

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: e-commerce-cluster

jobs:
  delete-infrastructure:
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_delete == 'DELETE'
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Delete EKS Cluster and VPC
      run: |
        # Get the list of nodegroups
        NODEGROUPS=$(aws eks list-nodegroups --cluster-name ${{ env.CLUSTER_NAME }} --query 'nodegroups[*]' --output text)

        # Delete each nodegroup
        for ng in $NODEGROUPS; do
          echo "Deleting nodegroup $ng"
          aws eks delete-nodegroup --cluster-name ${{ env.CLUSTER_NAME }} --nodegroup-name $ng
          aws eks wait nodegroup-deleted --cluster-name ${{ env.CLUSTER_NAME }} --nodegroup-name $ng
        done

        # Delete the EKS cluster
        echo "Deleting EKS cluster"
        aws eks delete-cluster --name ${{ env.CLUSTER_NAME }}

        # Wait for the cluster to be deleted
        echo "Waiting for cluster deletion"
        aws eks wait cluster-deleted --name ${{ env.CLUSTER_NAME }}

        # Delete the CloudFormation stack
        echo "Deleting CloudFormation stack"
        aws cloudformation delete-stack --stack-name ${{ env.CLUSTER_NAME }}

        # Wait for the stack to be deleted
        echo "Waiting for stack deletion"
        aws cloudformation wait stack-delete-complete --stack-name ${{ env.CLUSTER_NAME }}

    - name: Clean up resources
      run: |
        # Delete any leftover ELBs
        for lb in $(aws elb describe-load-balancers --query 'LoadBalancerDescriptions[*].LoadBalancerName' --output text); do
          aws elb delete-load-balancer --load-balancer-name $lb
        done

        # Delete any leftover EBS volumes
        for vol in $(aws ec2 describe-volumes --filters Name=status,Values=available --query 'Volumes[*].VolumeId' --output text); do
          aws ec2 delete-volume --volume-id $vol
        done